theme: jekyll-theme-minimal
title: Milena Bukal
description: >
  CS/Bioinformatics option Undergrad at the University of Waterloo 
  Currently in term 4A, expected graduation 2020

  Synesthete, nerd & sleep deprived

  milena.bukal@gmail.com
