theme: jekyll-theme-minimal
title: Milena Bukal
description: |
  CS/Bioinfo at University of Waterloo. 
  Term 4A, expected graduation 2020.
  Synesthete, nerd & sleep deprived.
  milena.bukal@gmail.com.
